#pragma once

#include "render/parma_guided_controls.hpp"

#include <array>
#include <cstdint>

namespace dtsx_decode {

// Native per-target descriptor generated by DTS_ParmaDec_SetGuided before it
// calls UpdateChannelInfo/UpdateDecodingAngles.  Source/target values are
// PARMA channel slots, never PCM channel indices.
struct ParmaGuidedNode final {
    std::uint8_t mode = 8U; // 0 direct, 1 pair, 2 triplet, 3 quadruplet
    std::uint8_t target = 31U;
    std::array<std::uint8_t, 4U> sources = {31U, 31U, 31U, 31U};
    float decoding_angle = -1.0F;
};

struct ParmaGuidedTopology final {
    std::array<ParmaGuidedNode, 11U> nodes{};
    std::uint32_t node_count = 0U;
};

[[nodiscard]] bool build_parma_guided_topology(
    const ParmaGuidedControls& controls,
    ParmaGuidedTopology& topology) noexcept;

} // namespace dtsx_decode
